import { CalendarEvent } from './types';

export const dummyEvents: CalendarEvent[] = [
  {
    id: '1',
    title: '라인 서류 마감',
    date: '2026-03-25',
    allDay: true,
    category: '채용공고',
    type: '마감',
    company: '라인',
    description: '서류 제출 마감일입니다.',
  },
  {
    id: '2',
    title: '토스페이먼츠 1차 면접',
    date: '2026-03-26',
    time: '14:00',
    category: '내 프로세스',
    type: '면접',
    company: '토스페이먼츠',
    location: '온라인 (Google Meet)',
    description: '기술 면접 준비 필요.',
  },
  {
    id: '3',
    title: '알고리즘 스터디',
    date: '2026-03-27',
    time: '19:00',
    category: '개인 일정',
    type: '스터디',
    location: '강남 스터디카페',
  },
  {
    id: '4',
    title: '카카오 백엔드 마감',
    date: '2026-03-28',
    allDay: true,
    category: '채용공고',
    type: '마감',
    company: '카카오',
    description: '백엔드 개발자 공채 서류 마감.',
  },
  {
    id: '5',
    title: '스터디 모임',
    date: '2026-03-31',
    time: '20:00',
    category: '개인 일정',
    type: '스터디',
  },
  {
    id: '6',
    title: '네이버 코딩테스트',
    date: '2026-04-02',
    time: '10:00',
    category: '내 프로세스',
    type: '코딩테스트',
    company: '네이버',
    description: '온라인 코딩테스트 2시간.',
  },
  {
    id: '7',
    title: '쿠팡 서류 마감',
    date: '2026-05-08',
    allDay: true,
    category: '채용공고',
    type: '마감',
    company: '쿠팡',
  },
  {
    id: '8',
    title: '배달의민족 1차 면접',
    date: '2026-05-14',
    time: '11:00',
    category: '내 프로세스',
    type: '면접',
    company: '배달의민족',
    location: '서울 송파구 배민 본사',
  },
  {
    id: '9',
    title: '알고리즘 스터디',
    date: '2026-05-20',
    time: '19:00',
    category: '개인 일정',
    type: '스터디',
  },
  {
    id: '10',
    title: '카카오 2차 면접',
    date: '2026-05-22',
    time: '15:00',
    category: '내 프로세스',
    type: '면접',
    company: '카카오',
    location: '온라인 (Zoom)',
  },
];
