import { KanbanCard } from './types';

export const dummyCards: KanbanCard[] = [
  {
    id: '1',
    company: '무신사',
    position: '브랜드 마케팅 인턴',
    appliedDate: '3/1',
    stageId: 'applied',
    tags: ['관심기업', '인턴'],
    nextAction: '서류 결과 대기',
    noResponseDays: 35,
    memo: '자기소개서 기반 질문 예상 답변 정리 필요',
  },
  {
    id: '2',
    company: '당근',
    position: '커뮤니티 운영 매니저',
    appliedDate: '3/12',
    stageId: 'applied',
    tags: ['정규직', '리모트'],
    nextAction: '채용 공고 마감 전 포트폴리오 보완',
  },
  {
    id: '3',
    company: '토스',
    position: '서비스 기획자',
    appliedDate: '3/5',
    stageId: 'screening',
    tags: ['정규직', '추천 채용'],
    nextAction: '결과 대기 중',
    noResponseDays: 14,
  },
  {
    id: '4',
    company: '현대자동차',
    position: '데이터 분석가',
    appliedDate: '3/15',
    stageId: 'screening',
    tags: ['대기업', '정규직'],
    nextAction: '온라인 인적성 일정 확인',
  },
  {
    id: '5',
    company: 'CJ ENM',
    position: '콘텐츠 전략',
    appliedDate: '3/8',
    stageId: 'process',
    tags: ['포트폴리오 제출'],
    nextAction: '사전 과제 제출 4/2',
    memo: '브랜드 사례 분석 슬라이드 10장 분량',
  },
  {
    id: '6',
    company: '우아한형제들',
    position: '프로덕트 디자이너',
    appliedDate: '3/10',
    stageId: 'interview',
    tags: ['관심기업', '정규직'],
    nextAction: '1차 면접 준비',
  },
  {
    id: '7',
    company: '카카오엔터테인먼트',
    position: '콘텐츠 마케터',
    appliedDate: '2/15',
    stageId: 'final-result',
    tags: ['정규직', '관심기업'],
    nextAction: '입사 조건 협의',
    finalResult: '합격',
  },
  {
    id: '8',
    company: '야놀자',
    position: '사업 개발',
    appliedDate: '2/20',
    stageId: 'final-result',
    tags: ['스타트업'],
    finalResult: '불합격',
  },
];
