import { KanbanCard } from './types';

export const dummyCards: KanbanCard[] = [
  {
    id: '1',
    company: '쿠팡',
    position: '풀스택 개발자',
    appliedDate: '3/1',
    stage: '지원완료',
    tags: ['대기업'],
    nextAction: '서류 결과 대기',
    noResponseDays: 35,
  },
  {
    id: '2',
    company: '라인',
    position: '서버 개발자',
    appliedDate: '3/12',
    stage: '지원완료',
    tags: ['외국계'],
    nextAction: '서류 결과 대기',
  },
  {
    id: '3',
    company: '카카오',
    position: '서버 개발자',
    appliedDate: '3/5',
    stage: '서류통과',
    tags: ['대기업'],
    nextAction: '결과 대기 중',
    noResponseDays: 14,
  },
  {
    id: '4',
    company: '비바리퍼블리카',
    position: '서버 개발자',
    appliedDate: '3/15',
    stage: '서류통과',
    tags: ['핀테크', '스타트업'],
    nextAction: '서류 결과 대기',
  },
  {
    id: '5',
    company: '네이버',
    position: '플랫폼 개발자',
    appliedDate: '3/8',
    stage: '코테/과제',
    tags: ['대기업', '백엔드'],
    nextAction: '코딩테스트 4/2',
  },
  {
    id: '6',
    company: '토스페이먼츠',
    position: '백엔드 개발자',
    appliedDate: '3/10',
    stage: '면접',
    tags: ['관심기업', '핀테크'],
    nextAction: '1차 면접 준비',
  },
  {
    id: '7',
    company: '당근마켓',
    position: '백엔드 개발자',
    appliedDate: '2/15',
    stage: '최종결과',
    tags: ['스타트업', '관심기업'],
    nextAction: '입사 조건 협의',
    finalResult: '합격',
  },
  {
    id: '8',
    company: '배달의민족',
    position: '백엔드 개발자',
    appliedDate: '2/20',
    stage: '최종결과',
    tags: ['스타트업'],
    finalResult: '불합격',
  },
];
